# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'
pod 'GoogleMaps'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end
