// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr5cShLFVbnWT7cfOCbyjEQOEx-bSnvmE',
    appId: '1:384750602652:web:19657c1842423f7823e059',
    messagingSenderId: '384750602652',
    projectId: 'fir-78ddd',
    authDomain: 'fir-78ddd.firebaseapp.com',
    storageBucket: 'fir-78ddd.appspot.com',
    measurementId: 'G-2JH4JRJQYL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo1k9N9R_G35tA_0oh0cFGphCWoWPSxvY',
    appId: '1:384750602652:android:d67b9d719e0b04e423e059',
    messagingSenderId: '384750602652',
    projectId: 'fir-78ddd',
    storageBucket: 'fir-78ddd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_NYPVLkaxhZ0naWJh_vyxtFPJ2jOezBA',
    appId: '1:384750602652:ios:28ca8ccdd7d2e3af23e059',
    messagingSenderId: '384750602652',
    projectId: 'fir-78ddd',
    storageBucket: 'fir-78ddd.appspot.com',
    iosClientId: '384750602652-45ssa81081hqtkulicau378gkc2b7uar.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_NYPVLkaxhZ0naWJh_vyxtFPJ2jOezBA',
    appId: '1:384750602652:ios:28ca8ccdd7d2e3af23e059',
    messagingSenderId: '384750602652',
    projectId: 'fir-78ddd',
    storageBucket: 'fir-78ddd.appspot.com',
    iosClientId: '384750602652-45ssa81081hqtkulicau378gkc2b7uar.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseListApp',
  );
}
